name = "bridgeworld"
compatibility_date = "2024-01-01"
pages_build_output_dir = ".next"

[env.production]
name = "bridgeworld"
compatibility_date = "2024-01-01"

[env.production.vars]
NODE_ENV = "production"
NEXT_PUBLIC_PORTAL_URL = "https://bridgeworld.lol"
CLOUDFLARE_ZONE_ID = "abdd28bf1af7e0d6d479c6ef016a05b8"
CLOUDFLARE_ACCOUNT_ID = "7e40a8af4a6129833c1cb6f5bcbfd662"
